2024-04-19 21:12:12,564 ERROR: Exception on /explore [GET] [in C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\dhana\Documents\Bluechip Tecnologies Asia\The Flask Mega-Tutorial\Chapter-09\app\routes.py", line 161, in explore
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\dhana\Documents\Bluechip Tecnologies Asia\The Flask Mega-Tutorial\Chapter-09\app\templates\index.html", line 24, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2024-04-19 21:12:13,882 ERROR: Exception on /explore [GET] [in C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\dhana\Documents\Bluechip Tecnologies Asia\The Flask Mega-Tutorial\Chapter-09\app\routes.py", line 161, in explore
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\dhana\Documents\Bluechip Tecnologies Asia\The Flask Mega-Tutorial\Chapter-09\app\templates\index.html", line 24, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2024-04-19 21:22:12,327 ERROR: Exception on /explore [GET] [in C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\dhana\Documents\Bluechip Tecnologies Asia\The Flask Mega-Tutorial\Chapter-09\app\routes.py", line 161, in explore
    flash(f'You are not following {username}.')
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\dhana\anaconda3\envs\ML_Environment\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\dhana\Documents\Bluechip Tecnologies Asia\The Flask Mega-Tutorial\Chapter-09\app\templates\index.html", line 24, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
